security:
    enable_authenticator_manager: true

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username
    password_hashers:
        # use your user class name here
        App\Entity\User:
            # Use native password hasher, which auto-selects the best
            # possible hashing algorithm (starting from Symfony 5.3 this is "bcrypt")
            algorithm: auto
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            provider: app_user_provider
            guard:
                authenticators:
                    - App\Security\UserAuthenticator
             # configure the maximum login attempts in a custom period of time
            #login_throttling:
               # max_attempts: 3
                #interval: '15 minutes'
            logout:
                path: app_logout
                # where to redirect after logout
                target: /
            entry_point: App\Security\AuthenticationEntryPoint
            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }

        - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/aboutUs, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/account/passwordReset, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/reset-password, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/password, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/email, roles: IS_AUTHENTICATED_ANONYMOUSLY }     
        - { path: ^/upload, roles: IS_AUTHENTICATED_ANONYMOUSLY }        
        - { path: ^/language, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/course/library, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/course/detail/*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/systemsetting/temsandconditions, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/course/mycourses, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/verification, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/course/remove, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/*, roles: ROLE_USER }

      
