INSERT INTO `permission` (`id`, `code`, `name`) VALUES 
(NULL, 'academic_level_list', 'academic_level_list'),
(NULL, 'academic_level_create', 'academic_level create'),
(NULL, 'academic_level_edit', 'academic_level edit'),
(NULL, 'academic_level_delete', 'academic_level delete'),
(NULL, 'content_list', 'content_list'),
(NULL, 'content_create', 'content create'),
(NULL, 'content_edit', 'content edit'),
(NULL, 'content_delete', 'content delete'),
(NULL, 'content_type_list', 'content_type_list'),
(NULL, 'content_type_create', 'content_type create'),
(NULL, 'content_type_edit', 'content_type edit'),
(NULL, 'content_type_delete', 'content_type delete'),
(NULL, 'country_list', 'country_list'),
(NULL, 'country_create', 'country create'),
(NULL, 'country_edit', 'country edit'),
(NULL, 'country_delete', 'country delete'),
(NULL, 'course_list', 'course_list'),
(NULL, 'course_create', 'course create'),
(NULL, 'course_edit', 'course edit'),
(NULL, 'course_delete', 'course delete'),
(NULL, 'course_category_list', 'course_category_list'),
(NULL, 'course_category_create', 'course_category create'),
(NULL, 'course_category_edit', 'course_category edit'),
(NULL, 'course_category_delete', 'course_category delete'),
(NULL, 'exam_list', 'exam_list'),
(NULL, 'exam_create', 'exam create'),
(NULL, 'exam_edit', 'exam edit'),
(NULL, 'exam_delete', 'exam delete'),
(NULL, 'instructor_list', 'instructor_list'),
(NULL, 'instructor_create', 'instructor create'),
(NULL, 'instructor_edit', 'instructor edit'),
(NULL, 'instructor_delete', 'instructor delete'),
(NULL, 'instructor_course_list', 'assigned course list'),
(NULL, 'instructor_course_create', 'assign courses to instructor'),
(NULL, 'instructor_course_edit', 'edit course assignement'),
(NULL, 'instructor_course_delete', 'delete assigned course'),
(NULL, 'chapter_list', 'chapter_list'),
(NULL, 'chapter_create', 'chapter create'),
(NULL, 'chapter_edit', 'chapter edit'),
(NULL, 'chapter_delete', 'chapter delete'),
(NULL, 'question_list', 'question_list'),
(NULL, 'question_create', 'question create'),
(NULL, 'question_edit', 'question edit'),
(NULL, 'question_delete', 'question delete'),
(NULL, 'quiz_list', 'quiz_list'),
(NULL, 'quiz_create', 'quiz create'),
(NULL, 'quiz_edit', 'quiz edit'),
(NULL, 'quiz_delete', 'quiz delete'),
(NULL, 'quiz_student_list', 'quiz_student_list'),
(NULL, 'quiz_student_create', 'quiz_student create'),
(NULL, 'quiz_student_edit', 'quiz_student edit'),
(NULL, 'quiz_student_delete', 'quiz_student delete'),
(NULL, 'student_list', 'student_list'),
(NULL, 'student_create', 'student create'),
(NULL, 'student_edit', 'student edit'),
(NULL, 'student_delete', 'student delete'),
(NULL, 'student_answer_list', 'student_answer_list'),
(NULL, 'student_answer_create', 'student_answer create'),
(NULL, 'student_answer_edit', 'student_answer edit'),
(NULL, 'student_answer_delete', 'student_answer delete'),
(NULL, 'student_course_list', 'student_course_list'),
(NULL, 'student_course_create', 'student_course create'),
(NULL, 'student_course_edit', 'student_course edit'),
(NULL, 'student_course_delete', 'student_course delete'),
(NULL, 'student_question_list', 'student_question_list'),
(NULL, 'student_question_create', 'student_question create'),
(NULL, 'student_question_edit', 'student_question edit'),
(NULL, 'student_question_delete', 'student_question delete'),
(NULL, 'student_quiz_list', 'student_quiz_list'),
(NULL, 'student_quiz_create', 'student_quiz create'),
(NULL, 'student_quiz_edit', 'student_quiz edit'),
(NULL, 'student_quiz_delete', 'student_quiz delete'),
(NULL, 'system_setting_list', 'system_setting_list'),
(NULL, 'system_setting_create', 'system_setting create'),
(NULL, 'system_setting_edit', 'system_setting edit'),
(NULL, 'system_setting_delete', 'system_setting delete'),
(NULL, 'user_list', 'user_list'),
(NULL, 'user_create', 'user create'),
(NULL, 'user_edit', 'user edit'),
(NULL, 'user_delete', 'user delete'),
(NULL, 'user_group_list', 'user_group_list'),
(NULL, 'user_group_create', 'user_group create'),
(NULL, 'user_group_edit', 'user_group edit'),
(NULL, 'user_group_delete', 'user_group delete'),
(NULL, 'user_profile_list', 'user_profile_list'),
(NULL, 'user_profile_create', 'user_profile create'),
(NULL, 'user_profile_edit', 'user_profile edit'),
(NULL, 'user_profile_delete', 'user_profile delete'),
(NULL, 'user_type_list', 'user_type_list'),
(NULL, 'user_type_create', 'user_type create'),
(NULL, 'user_type_edit', 'user_type edit'),
(NULL, 'user_type_delete', 'user_type delete'),
(NULL, 'choices_list', 'choices_list'),
(NULL, 'choices_create', 'choices create'),
(NULL, 'choices_edit', 'choices edit'),
(NULL, 'choices_delete', 'choices delete'),
(NULL, 'new_request_list', 'new request list'),
(NULL, 'rejected_request_list', 'rejected request list'),
(NULL, 'my_course', 'see own course'),
(NULL, 'manage_users', 'manage_users')
(NULL, 'approve_course_request', 'approve course request')
