INSERT INTO `user_type` (`id`, `name`, `description`) VALUES
(1, 'Admin', NULL),
(2, 'Director', NULL),
(3, 'Instructor', NULL),
(4, 'Student', NULL);

INSERT INTO `academic_level` (`id`, `name`, `description`) VALUES
(1, 'Bachelor', 'dsa'),
(2, 'Masters', 'da'),
(3, 'PhD', 'phd');


INSERT INTO `course_category` (`id`, `name`, `description`) VALUES
(1, 'Hardware', 'desc'),
(2, 'Hardware', NULL),
(3, 'Others', NULL);

INSERT INTO `user` (`id`, `user_type_id`, `username`, `roles`, `password`, `first_name`, `middle_name`, `last_name`, `email`, `is_active`, `last_login`, `locale`, `confirm_token`, `role`, `is_verified`) VALUES
(1, 1, 'admin', '["ROLE_ADMIN"]', '$2y$13$raJxMazDR0h64re5G7fmlecZdGdUmiUnFSLgmioAZllnJYspH5cLi', 'Admin', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0),
(3, 4, 'student', '["ROLE_STUDENT"]', '$2y$13$jAJlZw6Kzkv7zjd4KY/.GezpyfGH4S0asV7eD94Xn9kdN9KF4Kwbq', '333', '331', '331', 'lioulnebiye@gmail.comc', 1, '2021-10-19 15:55:49', '1', NULL, NULL, 1),
(19, NULL, 'neva1', '["ROLE_STUDENT"]', '$2y$13$IyRs0N9UaFrV2MxbI9qrm.9QbVP3O418T98.fwRSSkrXwZpz9GnT.', 'Nebiye', 'Lioul', 'Temesgen', 'lioulnebiye@gmail.com', 1, '2021-10-17 12:58:54', NULL, NULL, NULL, 1),
(23, 3, 'teacher', '["ROLE_USER"]', '$2y$13$a9QwjL7LtF4czVd9968a2OzlXONcJksSy2ilSclbnPVxTOmHefhO2', 'Teacher', 'teacher', 'teacher', 'teacher@gmail.com', 1, '2021-10-24 14:40:53', NULL, NULL, NULL, 0),
(24, 4, 'solasola', '["ROLE_USER"]', '$argon2id$v=19$m=65536,t=4,p=1$cp/8mHqw4rOp02ZP+M8a/Q$DFBLGx453oATu/w+yl/wjOKFOEHjz4Qf0/aBXXnWA4Y', 'sola', 'sola', 'sola', 'sola@gmail.com', 1, NULL, NULL, NULL, NULL, 0),
(31, NULL, 'yilo', '["ROLE_STUDENT"]', '$2y$13$9cKJr4DGb/f7tqTYL2ekW.b8Bjr9IGBXNVdLcEj97JtHN8JkTQ8HW', 'yilikal', 'tadesse', 'desta', 'yilo@gmail.com', 1, '2021-10-24 15:53:51', NULL, NULL, NULL, 0);



INSERT INTO `course` (`id`, `category_id`, `name`, `code`, `credit`, `description`, `status`) VALUES
(1, 1, 'Digital Logic', 'dd', NULL, 'Business professionals generally need at least a basic understanding of accounting, finance, marketing, human resources and information technology, and they often specialize in a practice area Business professionals generally need at least a basic understanding of accounting, finance, marketing, human resources and information technology, and they often specialize in a practice area', 1),
(2, 2, 'Programming Languages\n', NULL, NULL, 'this is management desccription', 1),
(3, 1, 'Electronics', NULL, NULL, 'Definition: Software engineering is a detailed study of engineering to the design, development and maintenance of software. Software engineering was introduced to address the issues of low-quality software projects. Problems arise when a software generally exceeds timelines, budgets, and reduced levels of quality.\r\n', 1),
(4, 2, 'Introduction Communication', NULL, NULL, 'Mechanical engineering is an engineering branch that combines engineering physics and mathematics principles with materials science to design, analyze, manufacture, and maintain mechanical systems. ... It is the branch of engineering that involves the design, production, and operation of machinery.', 1),
(5, 1, 'Electro Magnetic Field', NULL, NULL, 'An incentive is something that motivates individuals to do something. Economic incentives provide good value for money while also contributing to the societal organization. Restaurants, for example, offer discounts and buy one, get one promotion to persuade customers to dine at their establishments.\r\n\r\nA tradeoff occurs when one element or quality of something is traded in exchange for another aspect or quality of the same thing. In economics, a tradeoff is defined as the loss of the most desirable alternative, or the opportunity cost of a given option. The best illustration of a trade-off to choosing the most favored alternative is the relationship between unemployment and inflation.\r\n\r\nOpportunity cost is what everyone must give up acquiring something, and the benefit or value that was given up might pertain to decisions made in personal life, in the economy, or at the level of government. ', 1)




INSERT INTO `country` (`id`, `name`, `description`) VALUES
(2, 'Afghanistan', 'description'),
(3, 'Albania', 'description'),
(4, 'Algeria', 'description'),
(5, 'Andorra', 'description'),
(6, 'Angola', 'description'),
(7, 'Antigua and Barbuda', 'description'),
(8, 'Argentina', 'description'),
(9, 'Armenia', 'description'),
(10, 'Australia', 'description'),
(11, 'Austria', 'description'),
(12, 'Azerbaijan', 'description'),
(13, 'Bahamas (the)', 'description'),
(14, 'Bahrain', 'description'),
(15, 'Bangladesh', 'description'),
(16, 'Barbados', 'description'),
(17, 'Belarus', 'description'),
(18, 'Belgium', 'description'),
(19, 'Belize', 'description'),
(20, 'Benin', 'description'),
(21, 'Bhutan', 'description'),
(22, 'Bolivia', 'description'),
(23, 'Bosnia and Herzegovina', 'description'),
(24, 'Botswana', 'description'),
(25, 'Brazil', 'description'),
(26, 'Brunei Darussalam', 'description'),
(27, 'Bulgaria', 'description'),
(28, 'Burkina Faso', 'description'),
(29, 'Burundi', 'description'),
(30, 'Cabo Verde', 'description'),
(31, 'Cambodia', 'description'),
(32, 'Cameroon', 'description'),
(33, 'Canada', 'description'),
(34, 'Central African Republic (the)', 'description'),
(35, 'Chad', 'description'),
(36, 'Chile', 'description'),
(37, 'China', 'description'),
(38, 'Colombia', 'description'),
(39, 'Comoros (the)', 'description'),
(40, 'Congo (the)', 'description'),
(41, 'Costa Rica', 'description'),
(42, 'Côte dIvoire', 'description'),
(43, 'Croatia', 'description'),
(44, 'Cuba', 'description'),
(45, 'Cyprus', 'description'),
(46, 'Czechia', 'description'),
(47, 'Democratic Peoples Republic of Korea (the)', 'description'),
(48, 'Democratic Republic of the Congo (the)', 'description'),
(49, 'Denmark', 'description'),
(50, 'Djibouti', 'description'),
(51, 'Dominica', 'description'),
(52, 'Dominican Republic (the)', 'description'),
(53, 'Ecuador', 'description'),
(54, 'Egypt', 'description'),
(55, 'El Salvador', 'description'),
(56, 'Equatorial Guinea', 'description'),
(57, 'Eritrea', 'description'),
(58, 'Estonia', 'description'),
(59, 'Eswatini', 'description'),
(60, 'Ethiopia', 'description'),
(61, 'Fiji', 'description'),
(62, 'Finland', 'description'),
(63, 'France', 'description'),
(64, 'Gabon', 'description'),
(65, 'Gambia (the)', 'description'),
(66, 'Georgia', 'description'),
(67, 'Germany', 'description'),
(68, 'Ghana', 'description'),
(69, 'Greece', 'description'),
(70, 'Grenada', 'description'),
(71, 'Guatemala', 'description'),
(72, 'Guinea', 'description'),
(73, 'Guinea-Bissau', 'description'),
(74, 'Guyana', 'description'),
(75, 'Haiti', 'description'),
(76, 'Honduras', 'description'),
(77, 'Hungary', 'description'),
(78, 'Iceland', 'description'),
(79, 'India', 'description'),
(80, 'Indonesia', 'description'),
(81, 'Iran (Islamic Republic of)', 'description'),
(82, 'Iraq', 'description'),
(83, 'Ireland', 'description'),
(84, 'Israel', 'description'),
(85, 'Italy', 'description'),
(86, 'Jamaica', 'description'),
(87, 'Japan', 'description'),
(88, 'Jordan', 'description'),
(89, 'Kazakhstan', 'description'),
(90, 'Kenya', 'description'),
(91, 'Kiribati', 'description'),
(92, 'Kuwait', 'description'),
(93, 'Kyrgyzstan', 'description'),
(94, 'Lao Peoples Democratic Republic (the)', 'description'),
(95, 'Latvia', 'description'),
(96, 'Lebanon', 'description'),
(97, 'Lesotho', 'description'),
(98, 'Liberia', 'description'),
(99, 'Libya', 'description'),
(100, 'Liechtenstein', 'description'),
(101, 'Lithuania', 'description'),
(102, 'Luxembourg', 'description'),
(103, 'Madagascar', 'description'),
(104, 'Malawi', 'description'),
(105, 'Malaysia', 'description'),
(106, 'Maldives', 'description'),
(107, 'Mali', 'description'),
(108, 'Malta', 'description'),
(109, 'Marshall Islands (the)', 'description'),
(110, 'Mauritania', 'description'),
(111, 'Mauritius', 'description'),
(112, 'Mexico', 'description'),
(113, 'Micronesia (Federated States of)', 'description'),
(114, 'Monaco', 'description'),
(115, 'Mongolia', 'description'),
(116, 'Montenegro', 'description'),
(117, 'Morocco', 'description'),
(118, 'Mozambique', 'description'),
(119, 'Myanmar', 'description'),
(120, 'Namibia', 'description'),
(121, 'Nauru', 'description'),
(122, 'Nepal', 'description'),
(123, 'Netherlands (the)', 'description'),
(124, 'New Zealand', 'description'),
(125, 'Nicaragua', 'description'),
(126, 'Niger (the)', 'description'),
(127, 'Nigeria', 'description'),
(128, 'North Macedonia', 'description'),
(129, 'Norway', 'description'),
(130, 'Oman', 'description'),
(131, 'Pakistan', 'description'),
(132, 'Palau', 'description'),
(133, 'Panama', 'description'),
(134, 'Papua New Guinea', 'description'),
(135, 'Paraguay', 'description'),
(136, 'Peru', 'description'),
(137, 'Philippines (the)', 'description'),
(138, 'Poland', 'description'),
(139, 'Portugal', 'description'),
(140, 'Qatar', 'description'),
(141, 'Republic of Korea (the)', 'description'),
(142, 'Republic of Moldova (the)', 'description'),
(143, 'Romania', 'description'),
(144, 'Russian Federation (the)', 'description'),
(145, 'Rwanda', 'description'),
(146, 'Saint Kitts and Nevis', 'description'),
(147, 'Saint Lucia', 'description'),
(148, 'Saint Vincent and the Grenadines', 'description'),
(149, 'Samoa', 'description'),
(150, 'San Marino', 'description'),
(151, 'Sao Tome and Principe', 'description'),
(152, 'Saudi Arabia', 'description'),
(153, 'Senegal', 'description'),
(154, 'Serbia', 'description'),
(155, 'Seychelles', 'description'),
(156, 'Sierra Leone', 'description'),
(157, 'Singapore', 'description'),
(158, 'Slovakia', 'description'),
(159, 'Slovenia', 'description'),
(160, 'Solomon Islands', 'description'),
(161, 'Somalia', 'description'),
(162, 'South Africa', 'description'),
(163, 'South Sudan', 'description'),
(164, 'Spain', 'description'),
(165, 'Sri Lanka', 'description'),
(166, 'Sudan (the)', 'description'),
(167, 'Suriname', 'description'),
(168, 'Sweden', 'description'),
(169, 'Switzerland', 'description'),
(170, 'Syrian Arab Republic (the)', 'description'),
(171, 'Tajikistan', 'description'),
(172, 'Thailand', 'description'),
(173, 'Timor-Leste', 'description'),
(174, 'Togo', 'description'),
(175, 'Tonga', 'description'),
(176, 'Trinidad and Tobago', 'description'),
(177, 'Tunisia', 'description'),
(178, 'Turkey', 'description'),
(179, 'Turkmenistan', 'description'),
(180, 'Tuvalu', 'description'),
(181, 'Uganda', 'description'),
(182, 'Ukraine', 'description'),
(183, 'United Arab Emirates (the)', 'description'),
(184, 'United Kingdom of Great Britain and Northern Ireland (the)', 'description'),
(185, 'United Republic of Tanzania (the)', 'description'),
(186, 'United States of America (the)', 'description'),
(187, 'Uruguay', 'description'),
(188, 'Uzbekistan', 'description'),
(189, 'Vanuatu', 'description'),
(190, 'Venezuela (Bolivarian Republic of)', 'description'),
(191, 'Viet Nam', 'description'),
(192, 'Yemen', 'description'),
(193, 'Zambia', 'description'),
(194, 'Zimbabwe', 'description');

